#!/bin/sh
chmod +x /opt/eInfo/einfo.py
chown -R $USER /opt/eInfo/info

echo "ALL ALL=NOPASSWD: /opt/eInfo/einfo.py" > /etc/sudoers.d/einfo
chmod 0440 /etc/sudoers.d/einfo

if [ "`ping -c 1 google.com`" ]; then
    update-pciids
    update-usbids
fi
